name: sih_notifier
description: SIH client side notifier
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^1.1.0
  dio: ^3.0.9
  charts_flutter: ^0.8.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  firebase_messaging: ^6.0.16
  nearby_connections: 1.1.1+1
  pin_code_fields: ^4.0.0
  flutter_pusher: ^1.0.2
  overlay_support: ^1.0.5
  random_string: ^2.1.0

dev_dependencies:
  hive_generator: ^0.7.0+2
  flutter_launcher_icons: ^0.7.5
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_small.png"
  adaptive_icon_background: "assets/logo_small_white.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
